# Config file for lxce.d

[config]
	local-accept = "4449"
	local-ep     = "/lxce/"
	wimc-host    = "localhost"
	wimc-port    = "4449"
	mesh-port    = "4449"
	cSpace-configs = [
		      "boot_contained.json",
		      "service_contained.json",
		      "shutdown_contained.json"
		      ]

#nothing here.
