# Config file for lxce.d

[config]
	local-accept = "4449"
	local-ep     = "/lxce/"
	wimc-host    = "localhost"
	wimc-port    = "4449"
	mesh-port    = "4449"
	cSpace-configs = [
		      "capp/conf/boot_contained.json",
		      "capp/conf/service_contained.json",
		      "capp/conf/shutdown_contained.json"
		      ]

#nothing here.
