# Config file for mesh.d

[server-config]
	remote-accept = "9275"
	local-accept  = "4444"
	cert          = "/a/b/c/cert.crt"
	key           = "/x/y/z/pem.key"

[client-config]
	remote-ip-file = "./ip_file"
	remote-connect = "9275"
	local-accept   = "4440"
	cert           = "/a/b/x/cert.crt"
	key            = "/a/b/z/pem.key"
	
# this will be an array to support multiple entries (in future).
[reverse-proxy]
	http-path    = "/registry/"
	connect-ip   = "127.0.0.1"
	connect-port = "7777"
	enable       = "true"

#nothing here.
