# Config file for mesh.d

[server-config]
	remote-accept = "4443"
	local-accept  = "4444"
	cert          = "/a/b/c/cert.crt"
	key           = "/x/y/z/pem.key"

[client-config]
	remote-connect = "ws://127.0.0.1:4443/"
	local-accept   = "4440"
	cert           = "/a/b/x/cert.crt"
	key            = "/a/b/z/pem.key"

# configuration for reverse proxies. Only when proxy is enabled, otherwise
# these are ignored.

#[[reverse-proxy]]
#	server-name = "name-1"
#	end-point = "/metric"		# HTTP endpoint 
#	server-name = "127.0.0.1"	# sink
#	server-port = "7777"
#	enable = "true"			# true | false
#	
#[[reverse-proxy]]
#	server-name = "name-2"		# Unique name.
#	end-point = "/containers"	# unique end-point for sink
#	server-name = "127.0.0.1"
#	server-port = "7777"
#	enable = "false"		# true | false
	
#nothing here.
